config/routes.rb
IdeaPortal::Application.routes.draw do
  devise_for :users, :controllers => {:sessions => "sessions"}

    
    resources :ideas do
      member do
         post :create_comment
         post :increase_likes
         post :delete_like
         get :delete_idea
      end

      collection do
        get :show_ideas
        get :categoriwise_idea
      end
    end

    namespace :admin do |admin|
      resources :ideas
      resources :categories
    end

   root :to => 'ideas#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :ideas
  attr_accessible :name
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :idea

  attr_accessible :description
  validates_presence_of :description,:message => "Description can't be blank'"
  validates_length_of :description, :maximum => 200, :message => "description should be maximum 200 characters."
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :comments
  has_many :likes

  attr_accessible :description, :mode, :name, :status,:how_usefull,:category_id
  validates_presence_of :name,:message => "Name can't be blank"
  validates_presence_of :category_id,:message => "Please select a category"
 # validates_presence_of :mode,:message => "Please select at least one"
  validates_presence_of :description,:message => "Description can't be blank"
  validates_length_of :description, :maximum => 200, :message => "description should be maximum 200 characters."
  validates_presence_of :how_usefull,:message => "Can't be blank"
  validates_length_of :how_usefull, :maximum => 200, :message => "Please define it in maximum 200 characters."
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :idea
  attr_accessible :idea_id, :user_id

  scope :total_likes, lambda{|idea| where("idea_id =?", idea.id)}
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :idea
  attr_accessible :count,:idea_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  has_many :ideas
  has_many :likes

  attr_accessible :email, :emp_id, :name, :password, :password_confirmation, :remember_me, :is_admin
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
end

app/controllers/admin/ideas_controller.rb
class Admin::IdeasController < ApplicationController
	layout "admin"

	def index
		@ideas = Idea.all
	end

	def show
		@idea = Idea.find(params[:id])
		@comments = @idea.comments
		@total_likes = Like.total_likes(@idea).count
	end

	def destroy
		@idea = Idea.find(params[:id])
		@idea.destroy
		redirect_to admin_ideas_path
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_in_path_for(resource) 
  	logger.info "+++++++++++++++#{resource.inspect}"
  	if resource.is_admin?
			admin_ideas_path
		else
			ideas_path
		end

	end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_filter :authenticate_user!, :only => [:new, :create]

  def index
    @ideas = Idea.paginate(:page => params[:page], :per_page => 5)
  end

  def new
    @idea = Idea.new
  end

  def create
    @idea = current_user.ideas.new(params[:idea])
    if @idea.save
      flash[:notice] = "Successfully posted your idea"
      redirect_to idea_path(@idea)
    else
      logger.info "-------------#{@idea.errors.inspect}"
      render :action => "new"
    end
  end

  def edit
    @idea = Idea.find(params[:id])
  end

  def update
    @idea = Idea.find(params[:id])
    @idea.update_attributes(params[:idea])
    flash[:notice] = "Your Idea edited successfully"
    redirect_to idea_path(@idea)
  end

  def delete_idea
    Idea.find(params[:id]).delete
    flash[:notice] = "Your Idea deleted successfully"
    redirect_to ideas_path
  end

  def show
    @idea = Idea.find(params[:id])
    @like = Like.find_by_idea_id_and_user_id(params[:id],current_user.id)
    @comments = @idea.comments
    @comment = @idea.comments.new
  end

  def create_comment
    @idea = Idea.find(params[:id])
    @new_comment = @idea.comments.new(params[:comment])
    if @new_comment.save
      flash[:notice] = "Posted comment successfully."
    end
    @comments = @idea.comments
    respond_to do |format|
      format.js
    end
  end

  def increase_likes
    if params[:text] == "Like"
      likes = Like.new(:idea_id => params[:id],:user_id => current_user.id)
      likes.save
    else
      Like.where(:idea_id=>params[:id],:user_id=>current_user.id).delete_all
    end
    respond_to do |format|
      format.js{render :nothing=>true}
    end
  end


  def show_ideas
    if params[:my_ideas].present?
      @ideas = current_user.ideas.paginate(:page => params[:page], :per_page => 2)
    else
      @ideas = Idea.paginate(:page => params[:page], :per_page => 2)
    end

  end

  def categoriwise_idea
    category_id = Category.find_by_name(params[:type])
    @ideas = Idea.where(:category_id => category_id.id ).paginate(:page => params[:page], :per_page => 2)
    logger.info"##########{@ideas.inspect}"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

	def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message(:notice, :signed_in) if is_navigational_format?
    sign_in(resource_name, resource)
    if !session[:return_to].blank?
      redirect_to session[:return_to]
      session[:return_to] = nil
    else
      respond_with resource, :location => after_sign_in_path_for(resource)
    end
  end
  
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/ideas_helper.rb
module Admin::IdeasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def select_categories
    Category.select("id, name").collect{|i| [simple_format(i.name), i.id] }
  end

  def get_category(category_id)
    logger.info"######i m here#########"
    Category.find(category_id).name
  end

  def find_like(user_id,idea_id)
    Like.where(:user_id=>user_id, :idea_id => idea_id)
  end
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/admin/ideas/index.html.erb
<table>
  <thead>
    <tr>
    <th>Idea Name</th>
    <th>Created By</th>
    <th>Employee ID</th>
    <th>Status</th>
    <th>Created On</th>
    <th>Total Likes</th>
    <th>Action</th>
  </tr>
  </thead>
  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td>
          <%= link_to idea.name, admin_idea_path(idea) %>
        </td>
        <td>
          <%= idea.user.name %>
        </td>
        <td>
          <%= idea.user.emp_id %>
        </td>
        <td>
          <%= idea.status %>
        </td>
        <td>
          <%= idea.created_at.to_date %>
        </td>
        <td>
         <b> <%= Like.total_likes(idea).count %> </b>
        </td>
        <td>
          <%= link_to "Delete" , admin_idea_path(idea), :method => :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/ideas/show.html.erb
<div id="wrapper">
  <%= render "layouts/header" %>
  <div class="showDetails form-horizontal">
    <div class="control-group small ">
      <label class="control-label" for="inputEmail">Name :</label>
      <div class="controls ">
        <%= @idea.name %>
      </div>
    </div>
    <div class="control-group ">
      <label class="control-label" for="inputEmail">Category :</label>
      <div class="controls">
        <%= get_category(@idea.category_id)%>
      </div>
    </div>
    <div class="control-group small">
      <label class="control-label" for="inputEmail">Description :</label>
      <div class="controls">
        <%= @idea.description %>
      </div>
    </div>
    <div class="control-group small">
      <label class="control-label" for="inputEmail">How to Usefull :</label>
      <div class="controls">
        <%= @idea.how_usefull %>
      </div>
    </div>
    <div class="control-group small">
      <label class="control-label" for="inputEmail">Likes :</label> This idea got <%= @total_likes %> likes
    </div>
  </div>


  <div id="viewComments">
    <div id="comments">
    <div>
      <strong>Comments:</strong>
      <% if @comments.present?  %>
      <% @comments.each do |comment| %>
        <p class="comments"><%= comment.description %></p>
      <%end %>
      <% else %>
      No comments Yet
      <% end %>
    </div>

    </div>
  </div>

</div>

app/views/ideas/_comment.html.erb
<div>
  <strong>Comments:</strong>
  <% @comments.each do |comment| %>
    <p class="comments"><%= comment.description %></p>
<%end %>
</div>

app/views/ideas/categoriwise_idea.html.erb
<div id="wrapper">
  <%= render "layouts/header" %>
  <div class="ideaTab">
    <%= link_to "Cultural Ideas",categoriwise_idea_ideas_path(:type=>"Cultural"),:class=>"btn btn-primary"%>
    <%= link_to "Technical Ideas",categoriwise_idea_ideas_path(:type=>"Technical"),:class=>"btn btn-primary"%>
    <%= link_to "General Ideas",categoriwise_idea_ideas_path(:type=>"General"),:class=>"btn btn-primary"%>
  </div>
  <div id="displayIdea">
    <% if !@ideas.nil? %>
    <% @ideas.each do |i| %>
        <div class="ideaList">
          <div>
            <h3><%= i.name %></h3>
            <p><%= i.description %></p>
          </div>
          <%= link_to "view", idea_path(i.id) , :class => "blue_btn btn-primary btn-large" %>
          <div class="clear"></div>
        </div>
    <% end %>
        <% else %>
    <h2>No ideas present</h2>
    <% end %>
    <ul class="pagination">
      <%= will_paginate @ideas,:class => "customPagination" %>
    </ul>
  </div>
</div>

app/views/ideas/create_comment.js.erb
$("#viewComments #comments").html("<%= escape_javascript(render "comment") %>")
$("#new_comment").val('');
$("#commentForm").hide();

app/views/ideas/edit.html.erb
<%= form_for @idea, :class=>"centerform"  do |f| %>
    <% if @idea.errors.full_messages.any? %>
        <% @idea.errors.full_messages.each do |error_message| %>
            <%= error_message if @user.errors.full_messages.first == error_message %>
        <% end %>
    <% end %>
    <div class="control-group small">
      <div>
        <%= f.label :Name %>
      </div>
      <div class="controls">
        <%= f.text_field :name %>
      </div>
    </div>
    <div class="control-group small">
      <div>
        <%= f.label :Category %>
      </div>
      <div class="controls">
        <%= f.select(:category_id, select_categories, {:prompt => "-- Select a category --".html_safe}) %>
      </div>
    </div>
    <div class="control-group small">
      <div>
        <%= f.label :Description %>
      </div>
      <div class="controls">
        <%= f.text_area :description, :rows=>5, :columns=>10  %>
      </div>
    </div>
    <div class="control-group small">
      <div>
        <%= f.label :How_usefull %>
      </div>
      <div class="controls">
        <%= f.text_area :how_usefull,:rows=>5 %>
      </div>
    </div>
    <div class="control-group small">
      <div class="radio">
        <label>
          <%= f.radio_button :mode,'private' %>
          <!--<input type="radio" name="optionsRadios" id="optionsRadios1" value="option1">-->
          <%= f.label :Private %>
        </label>
      </div>
    </div>
    <div class="control-group small">
      <div class="radio">
        <label>
          <%= f.radio_button :mode,'public' %>
          <!--<input type="radio" name="optionsRadios" id="optionsRadios1" value="option1">-->
          <%= f.label :Public %>
        </label>
      </div>
    </div>
    <div class="control-group small">
      <div class="radio">
        <label>
          <%= f.radio_button :mode,'custom' %>
          <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1">
          <%= f.label :custom %>
        </label>
      </div>
    </div>
    <div class="row">
      <div class="span6">
        <%= f.submit "Edit your Idea",:class=>"btn btn-primary" %>
      </div>
    </div>
<% end %>

app/views/ideas/index.html.erb
<div id="wrapper" class="singn_in_body">
  <%= render "layouts/header" %>
<% if current_user.present? %>
      <div class="dashbord">

    <h3><span class="label">IDEAS</span></h3>
    <!--<span class="ideaSelectBox"><%#= select_tag "Filter", options_for_select(["All Ideas", "My Ideas", "Top 5 Ideas" ], "My Ideas"),:class=>"selectFilter" %></span>-->
    <% @ideas.each do |i| %>
        <div class="ideaList">
          <div>
            <div class="ideaName">
                <h3 style="float: left;"><%= i.name %></h3>
                <span class="label label-success">Likes :<%= Like.total_likes(i).count %></span>
            </div>
            <div style="clear:both;"></div>
            <p><%= i.description %></p>
          </div>
          <%= link_to "view", idea_path(i.id) , :class => "blue_btn btn-primary btn-large" %>
          <div class="clear"></div>
        </div>
    <% end %>


    <ul class="pagination">
      <%= will_paginate @ideas,:class => "customPagination" %>
    </ul>
<% else %>
      <section class="mainBg">
      </section>

      <footer class="footer">
      </footer>
<% end %>
  </div>
    </div>

app/views/ideas/new.html.erb
<%= form_for @idea, :class=>"centerform"  do |f| %>
   <div class="control-group small">
      <div>
        <%= f.label(:Name,"Name <em>*</em>".html_safe) %>
      </div>
      <div class="controls">
        <%= f.text_field :name %>
        <% unless @idea.errors[:name].blank? %>
            &nbsp; <div class="error_msg "><%= @idea.errors[:name].first  %></div>
        <% end %>
        <div class="clear"></div>
      </div>
    </div>
    <div class="control-group small">
      <div>
        <%= f.label(:Category,"Category <em>*</em>".html_safe) %>
      </div>
      <div class="controls">
        <%= f.select(:category_id, select_categories, {:prompt => "-- Select a category --".html_safe}) %>
        <% unless @idea.errors[:category_id].blank? %>
            &nbsp; <div class="error_msg "><%= @idea.errors[:category_id].first  %></div>
        <% end %>
      </div>
    </div>
    <div class="control-group small">
      <div>
        <%= f.label(:Description,"Description <em>*</em>".html_safe) %>
      </div>
      <div class="controls">
        <%= f.text_area :description, :rows=>5, :columns=>10  %>
        <% unless @idea.errors[:description].blank? %>
            &nbsp; <div class="error_msg "><%= @idea.errors[:description].first  %></div>
        <% end %>
      </div>
    </div>
    <div class="control-group small">
      <div>
        <%= f.label(:How_usefull,"How it usefull <em>*</em>".html_safe) %>
      </div>
      <div class="controls">
        <%= f.text_area :how_usefull,:rows=>5 %>
        <% unless @idea.errors[:how_usefull].blank? %>
            &nbsp; <div class="error_msg "><%= @idea.errors[:how_usefull].first  %></div>
        <% end %>
      </div>
    </div>
    <div class="control-group small">
      <div class="radio">
        <label>
          <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1">
          <%= f.label :Private %>
        </label>
      </div>
    </div>
    <div class="control-group small">
      <div class="radio">
        <label>
          <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1">
          <%= f.label :Public %>
        </label>
      </div>
    </div>
    <div class="control-group small">
      <div class="radio">
        <label>
          <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1">
          <%= f.label :custom %>
        </label>
      </div>
    </div>
    <div class="row">
      <div class="span6">
        <%= f.submit "Post"%>
      </div>
    </div>
<% end %>

app/views/ideas/show.html.erb
<div id="wrapper">
  <%= render "layouts/header" %>
  <div class="showDetails form-horizontal">
    <div class="control-group small ">
      <label class="control-label" for="inputEmail">Name :</label>
      <div class="controls ">
        <%= @idea.name %>
      </div>
    </div>
    <div class="control-group ">
      <label class="control-label" for="inputEmail">Category :</label>
      <div class="controls">
        <%= get_category(@idea.category_id)%>
      </div>
    </div>
    <div class="control-group small">
      <label class="control-label" for="inputEmail">Description :</label>
      <div class="controls">
        <%= @idea.description %>
      </div>
    </div>
    <div class="control-group small">
      <label class="control-label" for="inputEmail">How to Usefull :</label>
      <div class="controls">
        <%= @idea.how_usefull %>
      </div>
    </div>
    <div class="control-group small">
      <% if @idea.user_id != current_user.id %>
          <% if find_like(current_user.id,@idea.id).present? %>
              <%= link_to "Unlike", "javascript:void(0)",:class=>"btn btn-primary increaseLikes",:rel =>@idea.id   %>
          <% else %>
              <%= link_to "Like", "javascript:void(0)",:class=>"btn btn-primary increaseLikes",:rel =>@idea.id   %>
          <% end %>
      <% else %>
          <%= link_to "Edit", edit_idea_path,:class=>"btn btn-primary"   %>
          <%= link_to "Delete", delete_idea_idea_path(@idea),:class=>"btn btn-primary"   %>
      <% end %>
    </div>
  </div>


  <div id="viewComments">
    <div id="comments">
    <%= render :partial => "comment" %>
    </div>
    <div class="linkClick">
      <%= link_to "Add comments", "javascript:void(0)",:class =>"showComments"%>
    </div>
  </div>


  <div id="commentForm" style="display: none">
    <%= form_for @comment,:url=> create_comment_idea_path ,:method => "post",:remote => true  do |f| %>
        <div class="field">
          <%= f.label :Post_your_comment_here %><br />
          <%= f.text_area :description,:rows => 3,:id=>"new_comment" %>  <br/>
        </div> <br />

        <div class="actions">
          <%= f.submit :id=>"add_comment" %>
        </div>
    <% end %>
  </div>
</div>
<%= content_for :head do  %>
    <script type="text/javascript">
        $(document).ready(function(){
            $(".showComments").click(function(){
                $("#commentForm").show();
            });
        });

        $(".increaseLikes").click(function(){
            var id = $(this).attr("rel");
            var text = $(this).text();
            if(text == "Like"){
                $(this).text("Unlike");
            }
            else{
                $(this).text("Like");
            }

            $.ajax({
                type: 'POST',
                url: '/ideas/'+id+'/increase_likes',
                data:{id:id,text:text},
                dataType: 'script'
            })
        })
    </script>
<%end%>

app/views/ideas/show_ideas.html.erb
<div id="wrapper">
  <%= render "layouts/header" %>
  <% if !params[:rel].present? %>
    <div class="ideaTab">
        <%= link_to "Cultural Ideas",categoriwise_idea_ideas_path(:type=>"Cultural"),:class=>"btn btn-primary"%>
        <%= link_to "Technical Ideas",categoriwise_idea_ideas_path(:type=>"Technical"),:class=>"btn btn-primary"%>
        <%= link_to "General Ideas",categoriwise_idea_ideas_path(:type=>"General"),:class=>"btn btn-primary"%>
    </div>
  <% end %>
  <div id="displayIdea">
    <% @ideas.each do |i| %>
        <div class="ideaList">
          <div>
            <h3><%= i.name %></h3>
            <p><%= i.description %></p>
          </div>
          <%= link_to "view", idea_path(i.id) , :class => "blue_btn btn-primary btn-large" %>
          <div class="clear"></div>
        </div>
    <% end %>
    <ul class="pagination">
      <%= will_paginate @ideas,:class => "customPagination" %>
    </ul>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar-fixed-top mainHeader">
  <div class="container">
    <a href="#" class="logo">idea portal</a>
    <% if current_user %>
    <div class="navigation-links">
        <%= link_to "Post Your Idea", new_idea_path, :class=>"glyphicon glyphicon-eye-open" %>
        <%= link_to "View Ideas", show_ideas_ideas_path %>
        <%= link_to "My Ideas", show_ideas_ideas_path(:rel=>"my_ideas") %>
    </div>
    <div class="optionWrap clearfix">
      <% if current_user %>
        <% if current_user.is_admin? %>
          <%= link_to "Admin", admin_ideas_path, :class => "brand sign_links homeBtn" %> 
        <% end %>
          <%= link_to "Home", ideas_path, :class => "brand sign_links homeBtn" %>
           <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => "brand sign_links signOutBtn", :style=> "float:right;" %>
      <% else %>
          <%= link_to "Sign in", new_user_session_path, :class => "brand sign_links", :style=> "float:right;" %>
      <% end %>
    </div>
  </div>
</header>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "IdeaPortal" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "IdeaPortal", ideas_path, :class=>"brand" %>
          <% if current_user.is_admin? %>
            <span class="brand">Administrator</span>
          <% end %>
          <% if current_user %>
            <%= link_to "Home", ideas_path, :class => "brand sign_links homeBtn" %>
            <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => "brand sign_links", :style=> "float:right;" %>
          <% else %>
            <%= link_to "Sign in", new_user_session_path, :class => "brand sign_links", :style=> "float:right;" %>
          <% end %>
          <!--<div class="container nav-collapse">-->
            <!--<ul class="nav">-->
              <!--<li><%#= link_to "Link1", "/path1"  %></li>-->
              <!--<li><%#= link_to "Link2", "/path2"  %></li>-->
              <!--<li><%#= link_to "Link3", "/path3"  %></li>-->
            <!--</ul>-->
          <!--</div>&lt;!&ndash;/.nav-collapse &ndash;&gt;-->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span12">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <!--<div class="well sidebar-nav">-->
              <!--<h3>Sidebar</h3>-->
              <!--<ul class="nav nav-list">-->
                <!--<li class="nav-header">Sidebar</li>-->
                <!--<li><%#= link_to "Link1", "/path1"  %></li>-->
                <!--<li><%#= link_to "Link2", "/path2"  %></li>-->
                <!--<li><%#= link_to "Link3", "/path3"  %></li>-->
              <!--</ul>-->
            <!--</div>&lt;!&ndash;/.well &ndash;&gt;-->
          </div><!--/span-->
        </div><!--/row-->

      <!--<footer>-->
        <!--<p>&copy; Company 2013</p>-->
      <!--</footer>-->

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <%= yield :head %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]><html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]><html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]><html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "IdeaPortal" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->
    <!--[if gte IE 9]>

    <style type="text/css">
        .greenBtn, .greyBtn, .greenBtn:hover, .greyBtn:hover {
            filter: none;
        }
    </style>
    <![endif]-->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <% if current_user %>
        <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => "brand sign_links", :style=> "float:right;" %>
    <% else %>
        <%= link_to "Sign in", new_user_session_path, :class => "brand sign_links", :style=> "float:right;" %>
    <% end %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "IdeaPortal", ideas_path, :class=>"brand" %>

          <!--<div class="container nav-collapse">-->
            <!--<ul class="nav">-->
              <!--<li><%#= link_to "Link1", "/path1"  %></li>-->
              <!--<li><%#= link_to "Link2", "/path2"  %></li>-->
              <!--<li><%#= link_to "Link3", "/path3"  %></li>-->
            <!--</ul>-->
          <!--</div>&lt;!&ndash;/.nav-collapse &ndash;&gt;-->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span12">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <!--<div class="well sidebar-nav">-->
              <!--<h3>Sidebar</h3>-->
              <!--<ul class="nav nav-list">-->
                <!--<li class="nav-header">Sidebar</li>-->
                <!--<li><%#= link_to "Link1", "/path1"  %></li>-->
                <!--<li><%#= link_to "Link2", "/path2"  %></li>-->
                <!--<li><%#= link_to "Link3", "/path3"  %></li>-->
              <!--</ul>-->
            <!--</div>&lt;!&ndash;/.well &ndash;&gt;-->
          </div><!--/span-->
        </div><!--/row-->

      <!--<footer>-->
        <!--<p>&copy; Company 2013</p>-->
      <!--</footer>-->

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <%= yield :head %>
  </body>
</html>